// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"inkfinance.xyz/dal/model"
)

func newKeyValueCache(db *gorm.DB) keyValueCache {
	_keyValueCache := keyValueCache{}

	_keyValueCache.keyValueCacheDo.UseDB(db)
	_keyValueCache.keyValueCacheDo.UseModel(&model.KeyValueCache{})

	tableName := _keyValueCache.keyValueCacheDo.TableName()
	_keyValueCache.ALL = field.NewField(tableName, "*")
	_keyValueCache.ID = field.NewInt32(tableName, "id")
	_keyValueCache.KeyIs = field.NewString(tableName, "key_is")
	_keyValueCache.ValueIs = field.NewString(tableName, "value_is")

	_keyValueCache.fillFieldMap()

	return _keyValueCache
}

type keyValueCache struct {
	keyValueCacheDo keyValueCacheDo

	ALL     field.Field
	ID      field.Int32
	KeyIs   field.String
	ValueIs field.String

	fieldMap map[string]field.Expr
}

func (k keyValueCache) Table(newTableName string) *keyValueCache {
	k.keyValueCacheDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k keyValueCache) As(alias string) *keyValueCache {
	k.keyValueCacheDo.DO = *(k.keyValueCacheDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *keyValueCache) updateTableName(table string) *keyValueCache {
	k.ALL = field.NewField(table, "*")
	k.ID = field.NewInt32(table, "id")
	k.KeyIs = field.NewString(table, "key_is")
	k.ValueIs = field.NewString(table, "value_is")

	k.fillFieldMap()

	return k
}

func (k *keyValueCache) WithContext(ctx context.Context) *keyValueCacheDo {
	return k.keyValueCacheDo.WithContext(ctx)
}

func (k keyValueCache) TableName() string { return k.keyValueCacheDo.TableName() }

func (k keyValueCache) Alias() string { return k.keyValueCacheDo.Alias() }

func (k *keyValueCache) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *keyValueCache) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 3)
	k.fieldMap["id"] = k.ID
	k.fieldMap["key_is"] = k.KeyIs
	k.fieldMap["value_is"] = k.ValueIs
}

func (k keyValueCache) clone(db *gorm.DB) keyValueCache {
	k.keyValueCacheDo.ReplaceDB(db)
	return k
}

type keyValueCacheDo struct{ gen.DO }

func (k keyValueCacheDo) Debug() *keyValueCacheDo {
	return k.withDO(k.DO.Debug())
}

func (k keyValueCacheDo) WithContext(ctx context.Context) *keyValueCacheDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k keyValueCacheDo) Clauses(conds ...clause.Expression) *keyValueCacheDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k keyValueCacheDo) Returning(value interface{}, columns ...string) *keyValueCacheDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k keyValueCacheDo) Not(conds ...gen.Condition) *keyValueCacheDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k keyValueCacheDo) Or(conds ...gen.Condition) *keyValueCacheDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k keyValueCacheDo) Select(conds ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k keyValueCacheDo) Where(conds ...gen.Condition) *keyValueCacheDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k keyValueCacheDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *keyValueCacheDo {
	return k.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (k keyValueCacheDo) Order(conds ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k keyValueCacheDo) Distinct(cols ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k keyValueCacheDo) Omit(cols ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k keyValueCacheDo) Join(table schema.Tabler, on ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k keyValueCacheDo) LeftJoin(table schema.Tabler, on ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k keyValueCacheDo) RightJoin(table schema.Tabler, on ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k keyValueCacheDo) Group(cols ...field.Expr) *keyValueCacheDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k keyValueCacheDo) Having(conds ...gen.Condition) *keyValueCacheDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k keyValueCacheDo) Limit(limit int) *keyValueCacheDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k keyValueCacheDo) Offset(offset int) *keyValueCacheDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k keyValueCacheDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *keyValueCacheDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k keyValueCacheDo) Unscoped() *keyValueCacheDo {
	return k.withDO(k.DO.Unscoped())
}

func (k keyValueCacheDo) Create(values ...*model.KeyValueCache) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k keyValueCacheDo) CreateInBatches(values []*model.KeyValueCache, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k keyValueCacheDo) Save(values ...*model.KeyValueCache) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k keyValueCacheDo) First() (*model.KeyValueCache, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KeyValueCache), nil
	}
}

func (k keyValueCacheDo) Take() (*model.KeyValueCache, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KeyValueCache), nil
	}
}

func (k keyValueCacheDo) Last() (*model.KeyValueCache, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KeyValueCache), nil
	}
}

func (k keyValueCacheDo) Find() ([]*model.KeyValueCache, error) {
	result, err := k.DO.Find()
	return result.([]*model.KeyValueCache), err
}

func (k keyValueCacheDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KeyValueCache, err error) {
	buf := make([]*model.KeyValueCache, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k keyValueCacheDo) FindInBatches(result *[]*model.KeyValueCache, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k keyValueCacheDo) Attrs(attrs ...field.AssignExpr) *keyValueCacheDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k keyValueCacheDo) Assign(attrs ...field.AssignExpr) *keyValueCacheDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k keyValueCacheDo) Joins(field field.RelationField) *keyValueCacheDo {
	return k.withDO(k.DO.Joins(field))
}

func (k keyValueCacheDo) Preload(field field.RelationField) *keyValueCacheDo {
	return k.withDO(k.DO.Preload(field))
}

func (k keyValueCacheDo) FirstOrInit() (*model.KeyValueCache, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KeyValueCache), nil
	}
}

func (k keyValueCacheDo) FirstOrCreate() (*model.KeyValueCache, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KeyValueCache), nil
	}
}

func (k keyValueCacheDo) FindByPage(offset int, limit int) (result []*model.KeyValueCache, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k keyValueCacheDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k *keyValueCacheDo) withDO(do gen.Dao) *keyValueCacheDo {
	k.DO = *do.(*gen.DO)
	return k
}
