// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuditReport = "audit_reports"

// AuditReport mapped from table <audit_reports>
type AuditReport struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress      string `gorm:"column:dao_address" json:"dao_address"`
	ReportContent   []byte `gorm:"column:report_content" json:"report_content"`
	CreateTime      int64  `gorm:"column:create_time" json:"create_time"`
	UpdateTime      int64  `gorm:"column:update_time" json:"update_time"`
	OperatorAddress string `gorm:"column:operator_address" json:"operator_address"`
	BlockHeight     int64  `gorm:"column:block_height" json:"block_height"`
}

// TableName AuditReport's table name
func (*AuditReport) TableName() string {
	return TableNameAuditReport
}
