// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDaoInfo = "dao_info"

// DaoInfo mapped from table <dao_info>
type DaoInfo struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress string `gorm:"column:dao_address" json:"dao_address"`
	DaoLogo    string `gorm:"column:dao_logo" json:"dao_logo"`
}

// TableName DaoInfo's table name
func (*DaoInfo) TableName() string {
	return TableNameDaoInfo
}
