// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDaoUcvMapping = "dao_ucv_mapping"

// DaoUcvMapping mapped from table <dao_ucv_mapping>
type DaoUcvMapping struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress string    `gorm:"column:dao_address" json:"dao_address"`
	UcvAddress string    `gorm:"column:ucv_address" json:"ucv_address"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	Valid      int32     `gorm:"column:valid" json:"valid"`
}

// TableName DaoUcvMapping's table name
func (*DaoUcvMapping) TableName() string {
	return TableNameDaoUcvMapping
}
