// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDaoList = "dao_list"

// DaoList mapped from table <dao_list>
type DaoList struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress  string `gorm:"column:dao_address" json:"dao_address"`
	AdminWallet string `gorm:"column:admin_wallet" json:"admin_wallet"`
	BlockHeight int64  `gorm:"column:block_height" json:"block_height"`
	BlockTime   int64  `gorm:"column:block_time" json:"block_time"`
}

// TableName DaoList's table name
func (*DaoList) TableName() string {
	return TableNameDaoList
}
