// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExecuteMessage = "execute_message"

// ExecuteMessage mapped from table <execute_message>
type ExecuteMessage struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TopicID        string `gorm:"column:topic_id" json:"topic_id"`
	Address        string `gorm:"column:address" json:"address"`
	ExecProposalID string `gorm:"column:exec_proposal_id" json:"exec_proposal_id"`
	NowProposalID  string `gorm:"column:now_proposal_id" json:"now_proposal_id"`
	Message        string `gorm:"column:message" json:"message"`
}

// TableName ExecuteMessage's table name
func (*ExecuteMessage) TableName() string {
	return TableNameExecuteMessage
}
