// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKeyValueController = "key_value_controller"

// KeyValueController mapped from table <key_value_controller>
type KeyValueController struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	KeyIs   string `gorm:"column:key_is" json:"key_is"`
	ValueIs string `gorm:"column:value_is" json:"value_is"`
}

// TableName KeyValueController's table name
func (*KeyValueController) TableName() string {
	return TableNameKeyValueController
}
