// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProposalStatus = "proposal_status"

// ProposalStatus mapped from table <proposal_status>
type ProposalStatus struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress   string `gorm:"column:dao_address" json:"dao_address"`     // address
	ProposalType string `gorm:"column:proposal_type" json:"proposal_type"` // finance_other
	Status       int32  `gorm:"column:status" json:"status"`               // status=1 occupied status=0 can do
}

// TableName ProposalStatus's table name
func (*ProposalStatus) TableName() string {
	return TableNameProposalStatus
}
