// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProposalList = "proposal_list"

// ProposalList mapped from table <proposal_list>
type ProposalList struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DaoAddress  string `gorm:"column:dao_address" json:"dao_address"`
	ProposalID  string `gorm:"column:proposal_id" json:"proposal_id"`
	BlockHeight int64  `gorm:"column:block_height" json:"block_height"`
	BlockTime   int64  `gorm:"column:block_time" json:"block_time"`
	Category    string `gorm:"column:category" json:"category"`
	SubCategory string `gorm:"column:sub_category" json:"sub_category"`
	Expiration  int64  `gorm:"column:expiration" json:"expiration"`
}

// TableName ProposalList's table name
func (*ProposalList) TableName() string {
	return TableNameProposalList
}
