// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameScheduleWithdrawLog = "schedule_withdraw_logs"

// ScheduleWithdrawLog mapped from table <schedule_withdraw_logs>
type ScheduleWithdrawLog struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ScheduleID    int32  `gorm:"column:schedule_id" json:"schedule_id"`
	MemberAddress string `gorm:"column:member_address" json:"member_address"`
	TokenAddress  string `gorm:"column:token_address" json:"token_address"`
	ClaimAmount   string `gorm:"column:claim_amount" json:"claim_amount"`
	CreateTime    int64  `gorm:"column:create_time" json:"create_time"`
	DaoAddress    string `gorm:"column:dao_address" json:"dao_address"`
	CurrentTimeID int32  `gorm:"column:current_time_id" json:"current_time_id"`
	BlockHeight   int64  `gorm:"column:block_height" json:"block_height"`
}

// TableName ScheduleWithdrawLog's table name
func (*ScheduleWithdrawLog) TableName() string {
	return TableNameScheduleWithdrawLog
}
