// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScheduleMemberInfo = "schedule_member_info"

// ScheduleMemberInfo mapped from table <schedule_member_info>
type ScheduleMemberInfo struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ScheduleID  int32     `gorm:"column:schedule_id" json:"schedule_id"`
	MemberAddr  string    `gorm:"column:member_addr" json:"member_addr"`
	TokenAddr   string    `gorm:"column:token_addr" json:"token_addr"`
	CreateTime  time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time" json:"update_time"`
	Valid       int32     `gorm:"column:valid" json:"valid"`
	ListTitle   string    `gorm:"column:list_title" json:"list_title"`
	Description string    `gorm:"column:description" json:"description"`
	OncePay     string    `gorm:"column:once_pay" json:"once_pay"`
	DaoAddress  string    `gorm:"column:dao_address" json:"dao_address"`
}

// TableName ScheduleMemberInfo's table name
func (*ScheduleMemberInfo) TableName() string {
	return TableNameScheduleMemberInfo
}
