// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScheduleSignedInfo = "schedule_signed_info"

// ScheduleSignedInfo mapped from table <schedule_signed_info>
type ScheduleSignedInfo struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ScheduleID  int32     `gorm:"column:schedule_id" json:"schedule_id"`
	TimeID      int32     `gorm:"column:time_id" json:"time_id"`
	SignAddress string    `gorm:"column:sign_address" json:"sign_address"`
	CreateTime  time.Time `gorm:"column:create_time" json:"create_time"`
	DaoAddress  string    `gorm:"column:dao_address" json:"dao_address"`
	BlockTime   int64     `gorm:"column:block_time" json:"block_time"`
}

// TableName ScheduleSignedInfo's table name
func (*ScheduleSignedInfo) TableName() string {
	return TableNameScheduleSignedInfo
}
