// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSocialInfo = "social_info"

// SocialInfo mapped from table <social_info>
type SocialInfo struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SocialAccount string    `gorm:"column:social_account" json:"social_account"` // social account
	MediaType     string    `gorm:"column:media_type" json:"media_type"`         // twitter, discord…
	UserID        int32     `gorm:"column:user_id" json:"user_id"`
	CreateTime    time.Time `gorm:"column:create_time" json:"create_time"`
	Valid         int32     `gorm:"column:valid" json:"valid"`
	MainAccounts  string    `gorm:"column:main_accounts" json:"main_accounts"`
	ChainType     string    `gorm:"column:chain_type" json:"chain_type"`
	ChainID       int32     `gorm:"column:chain_id" json:"chain_id"`
}

// TableName SocialInfo's table name
func (*SocialInfo) TableName() string {
	return TableNameSocialInfo
}
