// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MainAccounts string    `gorm:"column:main_accounts" json:"main_accounts"` // address_account
	ChainType    string    `gorm:"column:chain_type" json:"chain_type"`       // eth,btc,avax
	ChainID      int32     `gorm:"column:chain_id" json:"chain_id"`           // chainID
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	Valid        int32     `gorm:"column:valid" json:"valid"` // 1=valid
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
