-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 15:07:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_inkfinance
-- -----------------------------------------------------
-- inkfinance db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inkfinance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inkfinance` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_inkfinance` ;



-- -----------------------------------------------------
-- Table `audit_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit_reports` ;

CREATE TABLE IF NOT EXISTS `audit_reports` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL,
  `report_content` LONGBLOB NULL DEFAULT NULL COMMENT 'report content as json',
  `create_time` BIGINT(20) NULL DEFAULT NULL COMMENT 'create time ',
  `update_time` BIGINT(20) NULL DEFAULT NULL COMMENT 'update time ',
  `operator_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'who operated',
  `block_height` BIGINT(11) NULL DEFAULT NULL COMMENT 'audit block',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `contract_events_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contract_events_progress` ;

CREATE TABLE IF NOT EXISTS `contract_events_progress` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contract_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'which contract address to scan',
  `events` VARCHAR(100) NULL DEFAULT NULL COMMENT 'which kind of event to scan',
  `start_height` BIGINT(11) NULL DEFAULT NULL COMMENT 'from which block to scan',
  `current_height` BIGINT(11) NULL DEFAULT NULL COMMENT 'the program scan to ',
  `valid` INT(11) NULL DEFAULT NULL,
  `update_time` DATETIME NULL DEFAULT NULL COMMENT 'when updated',
  `comments` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 173
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dao_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dao_list` ;

CREATE TABLE IF NOT EXISTS `dao_list` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `dao_address` VARCHAR(60) NULL DEFAULT NULL COMMENT 'dao address',
  `admin_wallet` VARCHAR(60) NULL DEFAULT NULL COMMENT 'admin’s wallet ',
  `block_height` BIGINT(20) NULL DEFAULT NULL COMMENT 'happened height',
  `block_time` BIGINT(20) NULL DEFAULT NULL COMMENT 'when created',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dao_ucv_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dao_ucv_mapping` ;

CREATE TABLE IF NOT EXISTS `dao_ucv_mapping` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'dao ',
  `ucv_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'ucv ',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT 'when created',
  `valid` INT(11) NULL DEFAULT NULL COMMENT '1=valid',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `execute_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `execute_message` ;

CREATE TABLE IF NOT EXISTS `execute_message` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `topic_id` VARCHAR(70) NULL DEFAULT NULL COMMENT 'topic id',
  `address` VARCHAR(80) NULL DEFAULT NULL COMMENT 'address',
  `exec_proposal_id` VARCHAR(70) NULL DEFAULT NULL COMMENT 'executed proposal',
  `now_proposal_id` VARCHAR(80) NULL DEFAULT NULL COMMENT 'current proposal',
  `message` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'execute message',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `key_value_cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `key_value_cache` ;

CREATE TABLE IF NOT EXISTS `key_value_cache` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `key_is` VARCHAR(200) NOT NULL COMMENT 'key',
  `value_is` VARCHAR(2000) NOT NULL COMMENT 'the value',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `proposal_decision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proposal_decision` ;

CREATE TABLE IF NOT EXISTS `proposal_decision` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'belong dao',
  `proposal_id` VARCHAR(100) NULL DEFAULT NULL COMMENT 'proposal id',
  `subcategory` VARCHAR(100) NULL DEFAULT NULL COMMENT 'subcategory',
  `update_time` DATETIME NULL DEFAULT NULL COMMENT 'when updated',
  `agree` SMALLINT(1) NULL DEFAULT NULL COMMENT '1=agree 0=disagree -1 not make decision yet',
  `new_proposal_height` BIGINT(11) NULL DEFAULT NULL COMMENT 'proposal block height',
  `audit_period` INT(11) NULL DEFAULT NULL COMMENT 'audit period, if it’s payment propsal',
  `agree_time` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT 'when make decision',
  `category` VARCHAR(50) NULL DEFAULT NULL COMMENT 'category',
  `expiration` BIGINT(20) NULL DEFAULT NULL COMMENT 'when the proposal expired',
  `proposal_title` VARCHAR(100) NULL DEFAULT NULL COMMENT 'title of the proposal',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 189
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `proposal_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proposal_status` ;

CREATE TABLE IF NOT EXISTS `proposal_status` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'proposal of the dao address',
  `proposal_type` VARCHAR(100) NULL DEFAULT NULL COMMENT 'eg: finance | other',
  `status` INT(11) NULL DEFAULT NULL COMMENT 'status=1 occupied status=0 can do',
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `schedule_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_info` ;

CREATE TABLE IF NOT EXISTS `schedule_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `schedule_id` INT(11) NULL DEFAULT NULL,
  `duration` BIGINT(11) NULL DEFAULT NULL,
  `schedule_times` BIGINT(11) NULL DEFAULT NULL,
  `start_time` BIGINT(11) NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `dao_address` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `schedule_member_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_member_info` ;

CREATE TABLE IF NOT EXISTS `schedule_member_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `schedule_id` INT(11) NULL DEFAULT NULL COMMENT 'schedule id ',
  `member_addr` VARCHAR(100) NULL DEFAULT NULL COMMENT 'member address',
  `token_addr` VARCHAR(100) NULL DEFAULT NULL COMMENT 'which token paid',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT 'when create',
  `update_time` DATETIME NULL DEFAULT NULL COMMENT 'when update',
  `valid` INT(11) NULL DEFAULT NULL COMMENT '1=valid',
  `list_title` VARCHAR(100) NULL DEFAULT NULL COMMENT 'title ',
  `description` VARCHAR(2000) NULL DEFAULT NULL COMMENT 'description',
  `once_pay` VARCHAR(50) NULL DEFAULT NULL COMMENT 'how much paid once time',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL COMMENT 'belong dao',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 300
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `schedule_signed_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_signed_info` ;

CREATE TABLE IF NOT EXISTS `schedule_signed_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `schedule_id` INT(11) NULL DEFAULT NULL,
  `time_id` INT(11) NULL DEFAULT NULL,
  `sign_address` VARCHAR(100) NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `dao_address` VARCHAR(100) NULL DEFAULT NULL,
  `block_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `schedule_withdraw_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_withdraw_logs` ;

CREATE TABLE IF NOT EXISTS `schedule_withdraw_logs` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `schedule_id` INT(11) NOT NULL COMMENT 'pay schedule id',
  `member_address` VARCHAR(100) NOT NULL COMMENT 'member address',
  `token_address` VARCHAR(100) NOT NULL COMMENT 'payed token',
  `claim_amount` VARCHAR(50) NULL DEFAULT NULL COMMENT 'claim amount',
  `create_time` BIGINT(20) NULL DEFAULT NULL COMMENT 'when this happened',
  `dao_address` VARCHAR(100) NULL DEFAULT NULL,
  `current_time_id` INT(11) NULL DEFAULT NULL COMMENT 'time id',
  `block_height` BIGINT(20) NULL DEFAULT NULL COMMENT 'block height when it happend',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `social_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_info` ;

CREATE TABLE IF NOT EXISTS `social_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increased id',
  `social_account` VARCHAR(200) NULL DEFAULT NULL COMMENT 'social account ',
  `media_type` VARCHAR(45) NULL DEFAULT NULL COMMENT 'twitter, discord…',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT 'user id, reference to [users]id',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT 'when created',
  `valid` INT(11) NULL DEFAULT NULL COMMENT '1=valid',
  `main_accounts` VARCHAR(200) NULL DEFAULT NULL COMMENT 'wallet address ',
  `chain_type` VARCHAR(50) NULL DEFAULT NULL COMMENT 'eth/avax/solana…etc.',
  `chain_id` INT(11) NULL DEFAULT NULL COMMENT 'chain id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 141
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `main_accounts` VARCHAR(200) NULL DEFAULT NULL COMMENT 'address_account',
  `chain_type` VARCHAR(45) NULL DEFAULT NULL COMMENT 'eth,btc,avax',
  `chain_id` INT(11) NULL DEFAULT NULL COMMENT 'chainID',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT 'when created',
  `valid` INT(11) NULL DEFAULT NULL COMMENT '1=valid',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 142
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
